version: "3.8"

networks:
  app:

services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.dev
  #   container_name: server
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./:/var/www/
  #     - /var/www/vendor
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql
  #   networks:
  #     - app-network
  # services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - app
  
  
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - app
  
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - "8008:80"
    volumes:
      - ./:/var/www/
      - /var/www/node_modules
    # depends_on:
    #   - "server"
    networks:
      - app
#Docker Networks

